### ISSUE TITLE
Stations switches only through web interface

### ISSUE THREAD

**Issue by vdlab** [karawin/KaRadio32_4#2]
I connected the free contacts of the wrover module to the volume, station switch, and the start / stop buttons. I corrected the csv file for my configuration, the volume buttons and start / stop work well, but the station switching buttons simply duplicate the volume buttons. Holding the C button has no effect. Then I checked the work with the encoders - same effect. Finally, I connect the IR receiver and configured the button codes for my remote, and...  volume works, the other buttons do not affect anything, although their codes are displayed confidently and stably in the terminal. Through the web interface everything works fine. Firmware v2.3 R0
p/s/ if I stop playback and then start it again, it will start from the first station in the playlist, regardless of which station was selected.

**Comment by karawin** [comment]
I will study it
Thanks

**Comment by vdlab** [comment]
The most difficult - after solving the problem, do not forget to describe how it was solved. So, if I flash this firmware into a new module, then all the described problems appear. If the firmware of earlier versions has already been written in this module, then everything works well.
