### ISSUE TITLE
Android Remote connect error

### ISSUE THREAD

**Issue by jeng37** [karawin/KaRadio32_4#4]
Hello,
Happy Easter to all,
Unfortunately, Android Remote no longer connects.
KaRadio32_4 TTGO-TM.
![Screenshot_1](https://user-images.githubusercontent.com/12857791/163727602-0e9e5050-23c5-400e-ba7a-cfc12728536f.jpg)

**Comment by karawin** [comment]
Sorry, it is a network problem, not a KaRadio bug.

**Comment by jeng37** [comment]
oh yeah thanks
How stupid of me, I had the ip and mac in the router config.
But that was from a different device.
sorry.
